name: app_turismo_tcc
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.1
  image_picker: ^0.6.1+4
  share: ^0.6.2+1
  esys_flutter_share: ^1.0.2
  flutter_splash_screen: ^0.1.0
  video_player: ^0.10.2+1
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^0.5.21+7
  permission_handler: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/boat-icon.png
   - assets/images/coconut-tree.png
   - assets/images/sun.png
   - assets/images/house.png
   - assets/images/power-button.png
   - assets/images/praias/praia-barra-santo-antonio.jpg
   - assets/images/praias/praia-garca-torta.jpg
   - assets/images/praias/praia-guaxuma.jpg
   - assets/images/praias/praia-ipioca.jpg
   - assets/images/praias/praia-jatiuca.jpg
   - assets/images/praias/praia-pajucara.jpg
   - assets/images/praias/praia-paripueira.jpg
   - assets/images/praias/praia-ponta-verde.jpg
   - assets/images/praias/litoral-sul/barra-sao-miguel.jpeg
   - assets/images/praias/litoral-sul/piacabucu.jpg
   - assets/images/praias/litoral-sul/praia-fances.jpg
   - assets/images/praias/litoral-sul/praia-gunga.jpg
   - assets/images/praias/litoral-sul/pontal-coruripe.jpg
   - assets/images/praias/litoral-norte/sao-miguel-dos-milagres.jpg
   - assets/images/praias/litoral-norte/porto-de-pedras.jpg
   - assets/images/praias/litoral-norte/porto-da-rua.jpg
   - assets/images/praias/litoral-norte/praia-japaratinga.jpg
   - assets/images/praias/litoral-norte/maragogi.jpg
   - assets/videos/intro.mp4
   - assets/images/login_image.jpeg
   - assets/images/comida-banner.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Agnetha
       fonts:
         - asset: assets/fonts/Agnetha.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
